SumaCubos/Models/Actions/Operation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SumaCubos.Models
{
	//public enum OperationType
	//{
		//Query,
		//Update
	//}
	public abstract class Operation
	{
		//public OperationType OperationType { get; set; }
		public string Key { get; set; }
		public string Name { get; set; }
		public List<int> Parameters { get; set; }
	}
	public class Query : Operation
	{
		public Query() {
			this.Key = "Q";
			this.Name = "QUERY";
			this.Parameters = new List<int>(6); //x1 y1 z1 x2 y2 z2
		}

	}
	public class Update: Operation
	{
		public Update() {
		this.Key = "U";
		this.Name = "UPDATE";
		this.Parameters = new List<int>(4); // x y z W
		}
	}
}

SumaCubos/Models/Input.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SumaCubos.Models
{
	public class Input
	{
		[Required(ErrorMessage = "El número de Casos de prueba es obligatorio")]
		[Range(1, 50, ErrorMessage = "El número de Casos de prueba debe estar entre 1 y 50")]
		public int T { get; set; } //Test Cases
		public List<InputCase> inputCases { get; set; }
	}
}

SumaCubos/Models/InputCase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SumaCubos.Models
{
	public class InputCase
	{

		[Required(ErrorMessage = "El tamaño de la matriz es obligatorio")]
		[Range(1, 100, ErrorMessage = "El tamaño de la matriz debe ser entre 1 y 100")]
		public int N { get; set; } //Matrix Lenght N*N*N
		[Required(ErrorMessage = "El numero de operaciones es obligatorio")]
		[Range(1, 1000, ErrorMessage = "El numero de operaciones debe ser entre 1 y 1000")]
		public int M { get; set; } //Number Of Operations
		public List<Operation> Operations { get; set; } 

	}
}

SumaCubos/Models/Space/Cube.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SumaCubos.Models
{
	public class Cube
	{
		public int x { get; set; }
		public int y { get; set; }
		public int z { get; set; }
		public int val { get; set; }
	}
}

SumaCubos/Models/Space/Matrix.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SumaCubos.Models
{
	public class Matrix
	{
		public Cube[][][] Cubes;
		public int N; //Limite de la matriz
	}
}

SumaCubos/Models/ValidationResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SumaCubos.Models
{
	public class ValidationResponse
	{
		public bool Success { get; set; }
		public List<String> ErrorMessages { get; set; }
	}
}

SumaCubos/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SumaCubos.Helpers;
using SumaCubos.Models;

namespace SumaCubos.Controllers
{
	public class MainController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Index(int T,string Commands)
		{
			var result = "";
			Input Input = InputProcessor.CreateInputCases(T,Commands);
			var ValidationErrors = InputProcessor.Validate(Input);
			if (ValidationErrors.Count == 0)
			{
				result = InputProcessor.ProcessCases(Input);
			}
			else {
				foreach (var error in ValidationErrors)
				{
					result += error.ErrorMessages;
				}
			}
			ViewBag.result = result;
			return View();
		}

	}
}

SumaCubos/Views/Main/Index.cshtml
@{
	ViewBag.Title = "Sumador de Cubos";
}
@section styles{
<style>

</style>
}
<div class="row">
	<div class="col-md-12">
		@using (Html.BeginForm("Index", "Main", FormMethod.Post))
		{

				<label for="T">T casos de prueba: </label><input type="number" name="T" id="T" class="form-control" min="1" max="50" value="1" onkeyup="this.value = minmax(this.value, 1, 50)"/ />
				<div id="testCases">
					<div id="case-0" class="test-case">
						<label> N tamaño de la matriz: </label><input type="number" name="N-0" id="N-0" class="form-control N" min="1" max="100" value="1" onchange="cambiarN(this,0)" onkeyup="this.value = minmax(this.value, 1, 100)" />
						<label> M Numero de operaciones: </label><input type="number" name="M-0" id="M-0" class="form-control M" min="1" max="1000" value="1" onchange="cambiarM(this,0)" onkeyup="this.value = minmax(this.value, 1, 1000)" />
						<div id="commandcases-0">
							<div id="command-0-0" class="command">
								<select id="commandType-0-0" class="commandType" onchange="cambiarCommand(this,0,0)">
									<option value="U" selected>UPDATE</option>
									<option value="Q">QUERY</option>
								</select>
								<div class="parameters" id="parameters-0-0">
									<label>x :</label><input type="number" name="x-0-0" id="x-0-0" min="1" value="1" class="x parameter" onchange="refreshCommandSummary()" />
									<label>y :</label><input type="number" name="y-0-0" id="y-0-0" min="1" value="1" class="y parameter" onchange="refreshCommandSummary()" />
									<label>z :</label><input type="number" name="z-0-0" id="z-0-0" min="1" value="1" class="z parameter" onchange="refreshCommandSummary()" />
									<label>W :</label><input type="number" name="W-0-0" id="W-0-0" min="1" value="1" class="W parameter" onchange="refreshCommandSummary()" />
								</div>
							</div>
						</div>
					</div>
				</div>
				<h2>Comandos</h2> 
				<h5>(Tambien se puede copiar y pegar aqui desde que respete el formato)</h5>
				<textarea style="" class="form-control" name="Commands" id="commandsSummary" rows="10">
1
1 1
UPDATE 1 1 1 1</textarea>
				<input type="submit" value="Procesar" />
				}
			</div>
		</div>
<div class="Row">
	<h2>Resultado</h2>
	<textarea name="resultado" rows="10">@ViewBag.result</textarea>
</div>
@section scripts{
<script>
	//T es el número de casos
	var T = 1;
	//al cambiar el numero de casos se imprime el formulario
	$("#T").change(cambiarT);
	$(".parameter").change(refreshCommandSummary);
	function cambiarT() {
		var T = $(this).val();
		if ($(this).val() > 50) {
			e.preventDefault();
			$(this).val(50);
		}
		$("#testCases").empty();
		for (var i = 0; i < T; i++) {
			var htmlapp = printTestCases(i);
			$("#testCases").append(htmlapp);
		}
		refreshCommandSummary();
	}

	function cambiarN(that, i) {
		var N = $(that).val();
		if ($(that).val() > 100) {
			e.preventDefault();
			$(that).val(100);
		}
		console.log("N:" + N);
		refreshCommandSummary("", N, "", i);
	}

	function cambiarM(that, i) {
		var M = $(that).val();
		if ($(that).val() > 1000) {
			e.preventDefault();
			$(that).val(1000);
		}
		var el = "#commandcases-" + i;
		$(el).empty();
		for (var j = 0; j < M; j++) {
			var htmlapp = printCommandCases(i, j);
			$(el).append(htmlapp);
		}
		refreshCommandSummary();
	}

	function cambiarCommand(that, i, j) {
		console.log("Commad:" + $(that).val());
		var commandType = $(that).val();
		var el = "#parameters-" + i + "-" + j;
		$(el).empty();
		var htmlapp = printCommandType(commandType, i, j);
		$(el).append(htmlapp);
		refreshCommandSummary();
	}

	function printTestCases(i) {
		var htmlapp = '<div id="case-' + i + '" class="test-case">';
		htmlapp += '<label> N tamaño de la matriz: </label> <input type="number" name="N-' + i + '" id="N-' + i + '" class="form-control N" min="1" max="100" value="1" onchange="cambiarN(this,' + i + ')" onkeyup="this.value = minmax(this.value, 1, 100)"/>';
		htmlapp += '<label> M Numero de operaciones: </label><input type="number" name="M-' + i + '" id="M-' + i + '" class="form-control M" min="1" max="1000" value="1" onchange="cambiarM(this,' + i + ')" onkeyup="this.value = minmax(this.value, 1, 1000)"/>';
		htmlapp += '<div id="commandcases-' + i + '">';
		htmlapp += printCommandCases(i, 0);
		htmlapp += '</div>';
		htmlapp += '</div>';
		return htmlapp;
	}
	function printCommandCases(i, j) {
		var htmlapp = '<div id="command-' + i + '-' + j + '" class="command"><select id="commandType-' + i + '-' + j + '" class="commandType" onchange="cambiarCommand(this,' + i + ',' + j + ')"><option value="U" selected>UPDATE</option><option value="Q">QUERY</option></select>';
		htmlapp += '<div class="parameters" id="parameters-' + i + '-' + j + '"><label>x :</label><input type="number" name="x-' + i + '-' + j + '" id="x-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>y :</label><input type="number" name="y-' + i + '-' + j + '" id="y-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>z :</label><input type="number" name="z-' + i + '-' + j + '" id="z-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>W :</label><input type="number" name="W-' + i + '-' + j + '" id="W-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/></div></div>';
		return htmlapp;
	}
	function printCommandType(commandType, i, j) {
		var htmlapp = '';
		if (commandType == 'U') {
			htmlapp += '<label>x :</label><input type="number" name="x-' + i + '-' + j + '" id="x-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>y :</label><input type="number" name="y-' + i + '-' + j + '" id="y-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>z :</label><input type="number" name="z-' + i + '-' + j + '" id="z-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>W :</label><input type="number" name="W-' + i + '-' + j + '" id="W-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/>';
		} else {
			if (commandType == 'Q') {
				htmlapp += '<label>x1 :</label><input type="number" name="x_1-' + i + '-' + j + '" id="x_1-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>y1 :</label><input type="number" name="y_1-' + i + '-' + j + '" id="y_1-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>z1 :</label><input type="number" name="z_1-' + i + '-' + j + '" id="z_1-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()" />';
				htmlapp += '<label>x2 :</label><input type="number" name="x_2-' + i + '-' + j + '" id="x_2-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>y2 :</label><input type="number" name="y_2-' + i + '-' + j + '" id="y_2-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/><label>z2 :</label><input type="number" name="z_2-' + i + '-' + j + '" id="z_2-' + i + '-' + j + '" min="1" value="1" class="parameter" onchange="refreshCommandSummary()"/>'
			}
		}
		return htmlapp;
	}
	function refreshCommandSummary() {

		var Summary = "";
		$("#commandsSummary").empty();
		var T = $("#T").val();
		Summary = T + "\n";
		var testCases = [];
		var Ns = [];
		var Ms = [];
		var Commands = [];
		i = 0;
		j = 0;
		$(".test-case").each(function (i, value) {
			var N = $("#N-" + i).val();
			var M = $("#M-" + i).val();
			Summary += N + " " + M + "\n";
			$("#commandcases-" + i + " .command").each(function (j, value) {
				var commandType = $("#commandType-" + i + "-" + j).val();
				console.log(commandType);
				if (commandType == 'U') {
					var x = $('#x-' + i + '-' + j).val();
					var y = $('#y-' + i + '-' + j).val();
					var z = $('#z-' + i + '-' + j).val();
					var W = $('#W-' + i + '-' + j).val();
					Summary += "UPDATE " + x + " " + y + " " + z + " " + W + "\n";
				} else {
					if (commandType == 'Q') {
						var x1 = $('#x_1-' + i + '-' + j).val();
						var y1 = $('#y_1-' + i + '-' + j).val();
						var z1 = $('#z_1-' + i + '-' + j).val();
						var x2 = $('#x_2-' + i + '-' + j).val();
						var y2 = $('#y_2-' + i + '-' + j).val();
						var z2 = $('#z_2-' + i + '-' + j).val();
						Summary += "QUERY " + x1 + " " + y1 + " " + z1 + " " + x2 + " " + y2 + " " + z2 + "\n";
					}
				}
			});
		});
		Summary = Summary.replace(/\n$/, "");
		console.log(Summary);
		$("#commandsSummary").val(Summary);
		console.log($("#commandsSummary").val());
	}
	function minmax(value, min, max) {
		if (parseInt(value) < min || isNaN(parseInt(value)))
			return min;
		else if (parseInt(value) > max)
			return max;
		else return value;
	}
</script>
}

SumaCubos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Sumadora de Cubos</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@RenderSection("Styles", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sumador de Cubos", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Julian Gómez Espinal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>